os: linux
dist: trusty
sudo: required
language: python
services: docker

before_install:
  # Install latest version of docker-ce and enable experimental features
  - sudo apt-get remove docker-engine
  - curl -O https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_17.05.0~ce-0~ubuntu-trusty_amd64.deb
  - echo "Y\n" | sudo dpkg -i docker-engine_17.05.0~ce-0~ubuntu-trusty_amd64.deb
  - echo "{"experimental":true}" | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - make build && make release
